export default {
  index: "What is Changesets?",
  "intro-to-using-changesets": "Intro to using changesets",
  "detailed-explanation": "Detailed explanation",
  "common-questions": "Common questions",
  "adding-a-changeset": "Adding a changeset",
  "automating-changesets": "Automating changesets",
  "checking-for-changesets": "Checking for changesets",
  "command-line-options": "Command line options",
  "config-file-options": "Config file options",
  decisions: "Decisions",
  dictionary: "Dictionary",
  "fixed-packages": "Fixed packages",
  "linked-packages": "Linked packages",
  "modifying-changelog-format": "Modifying changelog format",
  prereleases: "Prereleases",
  "problems-publishing-in-monorepos": "Problems publishing in monorepos",
  "snapshot-releases": "Snapshot releases",
  "versioning-apps": "Versioning applications and other non-npm packages",
  "experimental-options": "Experimental Options",
};
