export default {
  index: "什么是 changesets？",
  "intro-to-using-changesets": "changesets 使用简介",
  "detailed-explanation": "changesets 技术详解",
  "common-questions": "常见问题",
  "adding-a-changeset": "添加一个 changeset",
  "automating-changesets": "自动化 changesets",
  "checking-for-changesets": "检查 changesets",
  "command-line-options": "命令行选项",
  "config-file-options": "配置文件选项",
  decisions: "changesets 规则和决策设计",
  dictionary: "changesets 名词注释",
  "fixed-packages": "固定包",
  "linked-packages": "关联包",
  "modifying-changelog-format": "修改变更日志格式",
  prereleases: "预发行版",
  "problems-publishing-in-monorepos": "monorepos 中发布的问题",
  "snapshot-releases": "快照发布",
  "versioning-apps": "为应用程序和其他非 npm 包版本化",
  "experimental-options": "实验性选项",
};
